import "./globals.css";

export const metadata = {
  title: "조용운 포트폴리오",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
